# Generated by Django 3.2 on 2023-01-18 09:04

import apps.export_file.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadFileLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(apps.export_file.models.DownloadFileLog.StatusType['IN_PROCESS'], 0), (apps.export_file.models.DownloadFileLog.StatusType['SUCCESS'], 1), (apps.export_file.models.DownloadFileLog.StatusType['FAIL'], 2)], default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
