version: '3'

services:
  db:
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_0900_as_cs
    container_name: mysql-local-example
    image: mysql
    env_file:
      - .env
    ports:
      - ${MYSQL_PORT}:3306
    restart: always

  web:
    container_name: web-example
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:${WEB_PORT}"
    ports:
      - ${WEB_PORT}:8888
    restart: always
    depends_on:
      - db
    volumes:
      - .:/usr/src/app

  rabbitmq:
    restart: always
    image: rabbitmq:latest
    ports:
      - 5672:5672

  celery:
    restart: always
    build: .
    command: celery -A Example worker -l info
    depends_on:
      - rabbitmq
      - db
    volumes:
      - .:/usr/src/app

  celery-beat:
    restart: always
    build: .
    command: celery -A Example beat -l info -S django
    depends_on:
      - rabbitmq
      - db
    volumes:
      - .:/usr/src/app

  flower:
    build: .
    command: celery flower -A Example --broker=amqp://rabbitmq:5672//
    ports:
      - 5555:5555
    volumes:
      - .:/usr/src/app
    depends_on:
      - rabbitmq
      - db
