version: '3'

services:
  db:
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_0900_as_cs
    container_name: mysql-local-example
    image: mysql
    env_file:
      - .env
    ports:
      - ${MYSQL_PORT}:3306
    restart: always

  phpmyadmin:
    container_name: phpmyadmin-local-example
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - ${PHP_MY_ADMIN_PORT}:80
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn Example.wsgi:application --bind 0.0.0.0:8011
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    expose:
      - 8011
    restart: always
    depends_on:
      - db

  nginx:
    build: nginx/
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    ports:
      - 1221:80
    depends_on:
      - web

  rabbitmq:
    restart: always
    image: rabbitmq:latest
    ports:
      - 5672:5672

  celery:
    restart: always
    build: .
    command: celery -A Example worker -l info
    depends_on:
      - rabbitmq
      - db

  celery-beat:
    restart: always
    build: .
    command: celery -A Example beat -l info -S django
    depends_on:
      - rabbitmq
      - db

  flower:
    build: .
    command: celery flower -A Example --broker=amqp://rabbitmq:5672//
    ports:
      - 5555:5555
    depends_on:
      - rabbitmq
      - db

volumes:
  static_volume:
  media_volume:
#
##  postgres:
##    container_name: postgres_example
##    image: postgres
##    environment:
##      POSTGRES_USER: ${POSTGRES_USER}
##      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
##      POSTGRES_DB: ${POSTGRES_DB}
##    ports:
##      - ${POSTGRES_PORT}:5432
##    restart: always
#
##  pgadmin:
##    container_name: pgadmin_example
##    image: dpage/pgadmin4
##    environment:
##      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
##      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
##    depends_on:
##      - postgres
##    ports:
##      - ${PG_ADMIN_PORT}:80
##    restart: always

##remove all docker: sudo docker system prune
##put file .env === file docker-compose.yml ( .env file include environ variable)
##run in phpmyadmin
##ALTER USER 'admin' IDENTIFIED WITH mysql_native_password BY 'admin'
