# Generated by Django 3.2 on 2023-01-04 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('date_of_manufacture', models.DateTimeField()),
                ('author_book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_book', to='sample.author')),
                ('type_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_book', to='sample.typebook')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
