# Generated by Django 2.2.8 on 2020-05-26 14:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('date_of_manufacture', models.DateTimeField()),
                ('type_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_book', to='book.TypeBook')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
