# Generated by Django 3.2 on 2022-10-04 09:37

import apps.common.uuid_gen
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20200604_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.BigIntegerField(default=apps.common.uuid_gen.UuidGenerator.__next__, editable=False, primary_key=True, serialize=False),
        ),
    ]
