# Generated by Django 3.2 on 2022-11-18 08:02

import apps.common.uuid_gen
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.BigIntegerField(default=apps.common.uuid_gen.UuidGenerator.__next__, editable=False, primary_key=True, serialize=False),
        ),
    ]
