# Generated by Django 3.2 on 2022-11-22 10:51

import apps.common.uuid_gen
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_book_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.BigIntegerField(default=apps.common.uuid_gen.UuidGenerator.__next__, editable=False, primary_key=True, serialize=False),
        ),
    ]
