# Generated by Django 2.2.8 on 2020-06-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
