# Generated by Django 3.2 on 2022-12-16 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('quantity_question', models.IntegerField()),
                ('time', models.TimeField()),
                ('form', models.CharField(choices=[('Test', 'test'), ('Practice', 'practice')], default='Test', max_length=10)),
                ('recreate_question', models.BooleanField(default=True)),
                ('show_random_question', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(default=None, max_length=64)),
                ('exam_config_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_config', to='exams.examconfiguration')),
                ('question_id', models.ManyToManyField(related_name='exam_question', to='questions.Question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoryExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('number_of_question_correct', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_exam', to='exams.exams')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_exam_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='exams',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='exams.topic'),
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(0, 'Know'), (1, 'Understanding'), (2, 'Manipulate'), (3, 'High Manipulate')], default=0)),
                ('number', models.IntegerField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='questions.category')),
                ('exam_config_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='exams.examconfiguration')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
