# Generated by Django 2.2.8 on 2020-05-26 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('quantity_question', models.IntegerField()),
                ('time', models.TimeField()),
                ('form', models.CharField(choices=[('Test', 'test'), ('Practice', 'practice')], default='Test', max_length=10)),
                ('recreate_question', models.BooleanField(default=True)),
                ('show_random_question', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(default=None, max_length=64)),
                ('exam_config_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_config', to='exams.ExamConfiguration')),
                ('question_id', models.ManyToManyField(related_name='exam_question', to='questions.Question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoryExam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('score', models.IntegerField()),
                ('number_of_question_correct', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_exam', to='exams.Exams')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_exam_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='exams',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='exams.Topic'),
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('level', models.CharField(choices=[('Know', 'Know'), ('Understanding', 'Understanding'), ('Manipulate', 'Manipulate'), ('High Manipulate', 'High Manipulate')], default='Know', max_length=16)),
                ('number', models.IntegerField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='questions.Category')),
                ('exam_config_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='exams.ExamConfiguration')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
