# Generated by Django 3.2 on 2022-12-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_attributeproduct_booleanvalue_entityproduct_integervalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityproduct',
            name='is_visiable',
            field=models.BooleanField(default=False),
        ),
    ]
