# Generated by Django 3.2 on 2022-11-22 10:45

import apps.exportfile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadFileLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(apps.exportfile.models.DownloadFileLog.StatusType['IN_PROCESS'], 0), (apps.exportfile.models.DownloadFileLog.StatusType['SUCCESS'], 1), (apps.exportfile.models.DownloadFileLog.StatusType['FAIL'], 2)], default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
