# Generated by Django 2.2.8 on 2020-05-26 13:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RevokedToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('token', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
