# Generated by Django 3.1.1 on 2021-09-06 02:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_jwt', '0004_resetpasswordreferent'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetpasswordreferent',
            name='token',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resetpasswordreferent',
            name='code',
            field=models.CharField(max_length=255),
        ),
    ]
